### ISSUE TITLE
Syntax error (colon expected) with style attribute (in html template literal)

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/typescript-lit-html-plugin#19]
_From @ncodefun on July 15, 2018 21:32_

I'm reporting this here since it's this plugin that reports the error, but the context is that I work with lit-html and the vscode-lit-html extension ... So I have this:
![ts-styled-error](https://user-images.githubusercontent.com/35607086/42738591-2d6f804e-8854-11e8-9878-7bcc4fad6db9.png)

This only happens with the style attribute, and **only when the template string is multi-line**.  Tried with other styles before or after the expression and it doesn't work either (I thought maybe it looks for at least one colon/semi-colon pair).

_Copied from original issue: Microsoft/typescript-styled-plugin#64_

**Comment by anneb** [comment]
Below is a full example.   
Generates error for template_c:
 [ts-styled-plugin] colon expected


```
import {html} from '@polymer/lit-element';

const style = "color:red";
const template_a = html`<div style="color:red"></div>`;
const template_b = html`<div style="${style}"></div>`;
const template_c = html`<div 
style="${style}"></div>`;
```

**Comment by justinfagnani** [comment]
This has been annoying me recently. I think we need an option to turn off linting all together until the linters can correctly handle expressions.
