### ISSUE TITLE
The selected tag highlight does not work

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/typescript-lit-html-plugin#24]
_From @abdonrd on July 7, 2018 1:24_

![jul-07-2018 01-13-44](https://user-images.githubusercontent.com/1007051/42403684-31e35312-8183-11e8-8393-9392776c63da.gif)

_Copied from original issue: mjbvz/vscode-lit-html#41_

**Comment by abdonrd** [comment]
@mjbvz could you reopen the issue? Thanks in advance!

**Comment by mjbvz** [comment]
Works in TS 2.8-3.0. Broken in 3.1+

**Comment by mjbvz** [comment]
Should have been fixed cde819adbbdbbd5dc1a102b3526f5c6eb1a2ac08. Published as 0.7.1

**Comment by abdonrd** [comment]
Sorry @mjbvz, I just tried with the `v1.9.0` and I have the same behavior:

![nov-17-2018 00-46-38](https://user-images.githubusercontent.com/1007051/48652912-531c5500-ea02-11e8-8a56-5e8181a4470e.gif)

**Comment by mjbvz** [comment]
You need to be on VS Code 1.30 insiders. 24b0f75b1e33b88f30f2ed9d5b17ca60062c270b or newer

![screen shot 2018-11-16 at 3 57 22 pm](https://user-images.githubusercontent.com/12821956/48653203-6d314580-e9b8-11e8-88b0-cfa2e14be9e9.png)

**Comment by abdonrd** [comment]
Oh, yes! It works for me on last insiders! Thanks @mjbvz! 👏
